Update arch-install

diff --git a/bootstrap/arch-install b/bootstrap/arch-install
--- a/bootstrap/arch-install
+++ b/bootstrap/arch-install
@@ -6,6 +6,16 @@
 #
 ###############################################################################
 
+# Bash "strict" mode, -o pipefail removed
+SOURCED=false && [ "${0}" = "${BASH_SOURCE[0]}" ] || SOURCED=true
+if ! $SOURCED; then
+  set -eEu
+  shopt -s extdebug
+  trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+  IFS=$'\n\t'
+fi
+
+
 ###############################################################################
 # Text modifiers
 ###############################################################################
@@ -19,6 +29,15 @@ Reset="\033[0m"
 Red="\033[31m"
 Green="\033[32m"
 Yellow="\033[33m"
+
+
+###############################################################################
+# Paths
+###############################################################################
+WORKING_DIR=$(pwd)
+LOG="${WORKING_DIR}/arch-install.log"
+[[ -f ${LOG} ]] && rm -f "${LOG}"
+echo "Start log..." >>"${LOG}"
 
 
 ###############################################################################
